name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  provider: ^6.1.2

flutter:

  uses-material-design: true
  assets:
    - lib/images/
